### PR TITLE
TranslateDesktop: Add *.desktop.yaml translation option

### PR DESCRIPTION
**Pull request by palinek**
ref. lxqt/lxqt#1044

### CODE REVIEW

**Comment by yan12125** [comment]
How will desktop files with actions (e.g., https://github.com/lxqt/qterminal/blob/master/qterminal.desktop) be handled?

**Comment by stefonarch** [comment]
GTM

**Comment by palinek** [comment]
> merged

So is there a consensus that we will use the .yaml-s for desktop translations?

**Comment by tsujan** [comment]
> So is there a consensus that we will use the .yaml-s for desktop translations?

You, @stefonarch and @yan12125 know the details much more than I. So, I'll agree with any decision you make.

**Comment by stefonarch** [comment]
I'm fine with using yaml as I  [said](https://github.com/lxqt/lxqt/issues/1044#issuecomment-727159271).
Then  testing some components in weblate (qterminal, and then maybe lxqt-archiver first which has few translations atm).

**Comment by luis-pereira** [comment]
You guys now the details., much better than me.
Those who do the work, decide. I'm Ok with any decision you guys agree on.

**Comment by yan12125** [comment]
I'm fine with YAML as long as at least one LXQt member is willing to maintain the system in the long term. Speaking of this, @palinek do you want to be an admin at https://translate.lxqt-project.org/?

**Comment by palinek** [comment]
> I'm fine with YAML as long as at least one LXQt member is willing to maintain the system in the long term.

There is not much to maintain. I will convert all existing \*_lang.desktop into yamls, if you (all) give me a go.

> do you want to be an admin at https://translate.lxqt-project.org/?

I can't promise you to have time for this efforts.

**Comment by yan12125** [comment]
> There is not much to maintain.

Indeed, but it is better if YAML issues (if any) are taken care by those who has experience on YAML translations.

**Comment by palinek** [comment]
> who has experience on YAML translations.

And that's who? :) I just walked through the supported formats of weblate and picked one that is most easy to create/process by hand....

**Comment by stefonarch** [comment]
Transforming existing *xy.desktop file to yaml is easy, using Palinek's command line:
`for a in *.desktop; do echo 'weblate:' > "$a".yaml && sed -nre '/^[^=]+=/ { s/^([^=[]+).*=(.*)$/  \1: "\2"/; p; }' "$a" >> "$a".yaml; done`

Qterminal is in testing now, adding new hebrew translation created those 2 PR, the second one is very strange:

https://github.com/lxqt/qterminal/pull/742/files
https://github.com/lxqt/qterminal/commit/cab12bdceaa8ca494d75f096847b3ca740ff0bd5

My guess is that it needs a template.

**Comment by stefonarch** [comment]
I've seen this behavior: without a template weblate on creating a new translation weblate creates this
`{}` and only when committing translated text  to the the local repo it will appear the regular file. 

 I added now a template `qterminal.desktop.yaml`,  this will appear immediately.
```
Desktop Entry/Name: ""
Desktop Entry/GenericName: ""
Desktop Entry/Comment: ""
Desktop Action Dropdown/Name: ""
```
The _Monolingual base language file_ is now qterminal_en.desktop.yaml

Will create a PR for those 2 changes later. 
@palinek could you make a PR for lxqt-archiver with a template file and monolingual base file for further testing in weblate? Qterminal will be hardly get complete new translations.

@yan12125 Any idea why the bot has created those strange commits?
https://github.com/lxqt/qterminal/commit/cab12bdceaa8ca494d75f096847b3ca740ff0bd5

**Comment by palinek** [comment]
> The Monolingual base language file is now qterminal_en.desktop.yaml

The template is the one without `_lang` => qterminal.desktop.yaml. Didn't you configure weblate that way? (sorry to not mention it, but it seemed obvious to me)

**Comment by stefonarch** [comment]
Yes I know, and I configured weblate like that, taking it as monolingual file and without template file as in weblate docs.
 The issue is that weblate creates when creating new translation a file like that:
`{}`

and it ended up twice today as strange PR.

Creating a template file with empty strings and the base file as *_en.desktop.yaml seems solving that issue.
But more testing is needed, I did some manually qterminal but archiver would be good because it lacks most languages still.

**Comment by palinek** [comment]
> and without template file

Why without template file? The "component".desktop.yaml is a template file (and basic english strings).

**Comment by palinek** [comment]
Btw... created PRs for all of the components ... after reviewing... give me a go and I'll merge them.

**Comment by stefonarch** [comment]
In weblate docs the[ default for template](https://docs.weblate.org/en/latest/formats.html#yaml)  is "empty"  and doing so it creates this unusable file and commit. 

I see  that  using the same component.desktop.yaml  file for both should work:

Monolingual base language file
Template for new translations

Will merge lxqt-archiver and insert it for testing with that setting.

**Comment by yan12125** [comment]
> I see that using the same component.desktop.yaml file for both should work:

Is it the solution to empty files?

> Any idea why the bot has created those strange commits?
lxqt/qterminal@cab12bd

**Comment by stefonarch** [comment]
> Is it the solution to empty files?
> 
> >

Yes, creating a new translation the empty template is immediately in the local repo; but it happened  that   the translation  is not committed and weblate pushes the empty template.

**Comment by stefonarch** [comment]
>  give me a go and I'll merge them.

Today I merged this one and it looks fine, no strange mails anymore.
https://github.com/lxqt/qterminal/commit/c4dc2eaf70267324362671080905cf32524b26cd

Only thing to keep an eye on is that there _could_ be empty strings when a user creates a new translation and doesn't translate all, it will generate entries like that  in the final desktop file and items without text or tooltip.
`Name[xy]=""`

**Comment by stefonarch** [comment]
> after reviewing... give me a go and I'll merge them

https://github.com/lxqt/lxqt/issues/1495#issuecomment-734472101

**Pull request merged**
