### PR TITLE
Fix CMake export QTBUG-95791

### PR DESCRIPTION
**Pull request by gfgit**
See https://bugreports.qt.io/browse/QTBUG-95791

### CODE REVIEW

**Comment by gfgit** [comment]
`Qt6LinguistTools` is used also in other files but so far I fixed CMake errors with this change when compiling `lxqt-menu-data'

**Review by luis-pereira — APPROVED** [review]
GTM.

**Comment by luis-pereira** [comment]
Thanks @gfgit

**Comment by gfgit** [comment]
You're welcome

**Pull request merged**
