### PR TITLE
TranslateDesktop: Don't flush untranslated strings

### PR DESCRIPTION
**Pull request by palinek**
ref. https://github.com/lxqt/lxqt-build-tools/pull/59#issuecomment-733128769

### CODE REVIEW

**Comment by palinek** [comment]
@stefonarch Please, don't use the "squash and merge" button any more....

**Comment by stefonarch** [comment]
Sorry, but every time I merge weblate commits I'm supposed to use that exact  button and no other.
I'm fine with touching nothing, but please be clear all of you in explaining.

**Comment by stefonarch** [comment]
GTM

> Please, don't use the "squash and merge" button any more....

Did you mean this in this repo or in general?

**Comment by tsujan** [comment]
@stefonarch 
I've never encountered a problem with "squash and merge" button except for a single case. So, I consider it very safe.

Of course, @palinek might want to tell about his experience.

**Comment by palinek** [comment]
> Did you mean this in this repo or in general?

I meant it general.

> Of course, @palinek might want to tell about his experience.

Example #59 
- this was in PR
```
* commit 54fee5d2a56be398564f81e821628f028ad7034f (origin/desktop_translate, desktop_translate)
| Author: Palo Kisa <palo.kisa@gmail.com>
| Date:   Fri Nov 13 10:53:48 2020 +0100
| 
|     TranslateDesktop: Add *.desktop.yaml translation option
| 
* commit 182fcce11762749c80dbe0f8d51bc254aa9af1f3
| Author: Palo Kisa <palo.kisa@gmail.com>
| Date:   Thu Nov 12 23:19:20 2020 +0100
| 
|     TranslateDesktop: Drop deprecated *.tx.sh generation
|   
*   commit bf7e4b9c7ee91106b844741251e4f98cfdfc1088 (tag: 0.8.0)
|\  Merge: 8a25a34 09016e0
```
- and this is after merging in master
```
* commit 133f8392342cffc5df007e062210e89f18624faf (origin/master, origin/HEAD)
| Author: palinek <palinek@users.noreply.github.com>
| Date:   Wed Nov 18 09:06:24 2020 +0100
| 
|     TranslateDesktop: Add *.desktop.yaml translation option (#59)
|     
|     * TranslateDesktop: Drop deprecated *.tx.sh generation
|     
|     * TranslateDesktop: Add *.desktop.yaml translation option
|   
*   commit bf7e4b9c7ee91106b844741251e4f98cfdfc1088 (tag: 0.8.0)
|\  Merge: 8a25a34 09016e0
| | Author: tsujan <tsujan2000@gmail.com>
```

=> so instead of the original author `Palo Kisa <palo.kisa@gmail.com>` there is github's alias user `palinek <palinek@users.noreply.github.com>`

**Comment by tsujan** [comment]
Counterexample (https://github.com/lxqt/pcmanfm-qt/pull/1200):

```
commit 4f0d7638fd574b2326994215c96d10c4a9fe37f4
Author: tsujan <tsujan2000@gmail.com>
Date:   Wed Oct 7 20:47:18 2020 +0330

    Keep current focus when opening new tab in background (#1200)
    
    * Keep current focus when opening new tab in background
    
    Previously, the new tab took away the focus in the background and that could be quite confusing, especially when the keyboard was used.
    
    * Removed a redundant `return`
```

**Comment by palinek** [comment]
> Counterexample (lxqt/pcmanfm-qt#1200):

..and that's also wrong, see the original commits:
```
* commit c64f1cad209ccc4748cd5ec5d63eb399b42da12b (HEAD -> pr_1200)
| Author: Tsu Jan <tsujan2000@gmail.com>
| Date:   Sun Oct 4 01:04:49 2020 +0330
| 
|     Removed a redundant `return`
| 
* commit 453e02dfd2c19e3f3eef92d57e9a77e7e43d4885
| Author: Tsu Jan <tsujan2000@gmail.com>
| Date:   Sat Sep 26 17:51:26 2020 +0330
| 
|     Keep current focus when opening new tab in background
|     
|     Previously, the new tab took away the focus in the background and that could be quite confusing, especially when the keyboard was used.
| 
* commit cbcff777e9f035260859d1de0fd739a279f4078f
```

Your name is screwed to the nickname in github. However you mail address is correct.... maybe because of preferences in your github profile.

Anyway github is not preserving the authorship in original commits but is rather creating commit with the gihub's info of the PR creator.

**Comment by tsujan** [comment]
> maybe because of preferences in your github profile.

Exactly what I wanted to say about your profile ;)

> Anyway github is not preserving the authorship in original commits

Have you seen any report about that (I didn't have time to search)? I think what you see may be about the profile.

**Comment by tsujan** [comment]
> Your name is screwed to the nickname in github

"Tsu Jan" is also a nickname; I set my profile as fast as possible ;) But you motivated me to read github doc -- when I find the time.

**Comment by palinek** [comment]
> **Keep my email addresses private**
> We’ll remove your public profile email and use palinek@users.noreply.github.com when performing web-based Git operations (e.g. edits and merges) and sending email on your behalf. If you want command line Git operations to use your private email you must set your email in Git.

...well it's not a bug, but a feature :)

**Comment by tsujan** [comment]
> Keep my email addresses private...

Some setting should also exist for "Tsu Jan" instead of "tsujan", although it isn't important in my case.

**Comment by palinek** [comment]
It's even worse for the weblate commits...as the PRs are created by LXQtBot user...so the authorship is lost, e.g.:
```
* commit d5698bf99eedcecd8cda697270987b3ede19b42a (HEAD -> master, origin/master)
| Author: LXQtBot <72348767+LXQtBot@users.noreply.github.com>
| Date:   Sun Nov 22 00:11:04 2020 +0800
| 
|     Translations update from Weblate (#682)
|     
|     * Weblate commits
|     
|     Co-authored-by: Moo <hazap@hotmail.com>
|     Translate-URL: https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-config-appearance/lt/
|     Translate-URL: https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-config-brightness/lt/
|     Translate-URL: https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-config-file-associations/lt/
|     Translate-URL: https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-config-input/lt/
|     Translate-URL: https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-config-monitor/lt/
|     Translation: LXQt Configuration/lxqt-config-appearance
|     Translation: LXQt Configuration/lxqt-config-brightness
|     Translation: LXQt Configuration/lxqt-config-file-associations
|     Translation: LXQt Configuration/lxqt-config-input
|     Translation: LXQt Configuration/lxqt-config-monitor
|     
|     * Weblate commits
|     
|     Co-authored-by: Sérgio Marques <smarquespt@gmail.com>
|     Translate-URL: https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-config-appearance/pt/
|     Translate-URL: https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-config-brightness/pt/
|     Translate-URL: https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-config-file-associations/pt/
|     Translate-URL: https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-config-input/pt/
|     Translate-URL: https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-config-monitor/pt/
|     Translation: LXQt Configuration/lxqt-config-appearance
|     Translation: LXQt Configuration/lxqt-config-brightness
|     Translation: LXQt Configuration/lxqt-config-file-associations
|     Translation: LXQt Configuration/lxqt-config-input
|     Translation: LXQt Configuration/lxqt-config-monitor
|     
|     * Weblate commits
|     
|     Co-authored-by: Arthur Borsboom <arthurborsboom@gmail.com>
|     Translate-URL: https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-config-brightness/nl/
|     Translation: LXQt Configuration/lxqt-config-brightness
|     
|     Co-authored-by: Moo <hazap@hotmail.com>
|     Co-authored-by: Sérgio Marques <smarquespt@gmail.com>
|     Co-authored-by: Arthur Borsboom <arthurborsboom@gmail.com>
| 
* commit ab3ab3b3b16c70850315db9dc7678ba530e0c2e5
| Author: LXQtBot <72348767+LXQtBot@users.noreply.github.com>
| Date:   Fri Nov 20 02:35:38 2020 +0800
| 
|     Weblate commits (#680)
|     
|     Co-authored-by: Daniel Fischer <fischer049@gmail.com>
|     Translate-URL: https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-config-appearance/de/
|     Translation: LXQt Configuration/lxqt-config-appearance
|     
|     Co-authored-by: Daniel Fischer <fischer049@gmail.com>
| 
* commit f22cee687bf186d5c1875ae921331c7ba0cc4955 (tag: 0.16.1)
```

**Comment by tsujan** [comment]
> It's even worse for the weblate commits

Why "worse"? Which email address should be put there?

BTW, your email notifications were always from "palinek"; this one had your real name as the sender.

**Comment by palinek** [comment]
> Why "worse"? Which email address should be put there?

Those commits should never be squashed to preserve authorship of the translator.

**Comment by stefonarch** [comment]
We agreed to use co-authoring, if I remember well.

But yes, the old weblate commits were different:
https://github.com/lxqt/pcmanfm-qt/pull/1084/commits

EDIT: maybe not, they look the same:
https://github.com/lxqt/pcmanfm-qt/pull/1230/commits
`
username authored and weblate committed 15 days ago
`

So I'll wait for all to agree how to merge translation PRs from LXQtBot, they are eight atm.

**Comment by tsujan** [comment]
> So I'll wait for all to agree how to merge translation PRs from LXQtBot

I say, the way you did before. Really, nothing has changed.

**Pull request merged**
