### PR TITLE
Adds CMake find modules for some xdg-utils tools

### PR DESCRIPTION
**Pull request by luis-pereira**
xdg-mime, xdg-open, xdg-email and xdg-settings.

### CODE REVIEW

**Comment by tsujan** [comment]
@luis-pereira 
Is this finished and can it be merged before the next release (0.7.0)?

**Comment by luis-pereira** [comment]
@tsujan It's finished and can be merged.
Still in progress work always start with WIP.

**Comment by jubalh** [comment]
>  Still in progress work always start with WIP.

When creating a pull request on GitHub one can also use 'create draft' (grey) or similar. And once the PR is ready to be reviewed or merged one can change to regular PR (green).

**Comment by luis-pereira** [comment]
@jubalh Thank's. Is the Draft a recent thing ? I don't remember seeing it.

**Comment by jubalh** [comment]
Yes, I think it got added some months ago :-)
It definitely wasn't there in the beginning. But it's quite handy!

**Pull request merged**
