### PR TITLE
Update minimum versions

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by stefonarch** [comment]
Update `set(LXQT_MIN_LINGUIST_VERSION "6.3")` too?

**Review by tsujan — APPROVED** [review]
GTM

**Comment by tsujan** [comment]
> Update set(LXQT_MIN_LINGUIST_VERSION "6.3") too?

Where is it?

**Comment by stefonarch** [comment]
> > Update set(LXQT_MIN_LINGUIST_VERSION "6.3") too?
> 
> Where is it?

In the `CMakeList.txt` here.

**Comment by tsujan** [comment]
OK, it can be added.

**Comment by stefonarch** [comment]
Maybe we should also update the Readme, explainin  lxqt2-build-tools and Qt5 version in a second PR. Ideally it should provide both versions.

**Comment by tsujan** [comment]
We won't update the older version, and we want to say goodbye to Qt5.

Of course, for a long time, users might need to keep Qt5-based packages of libqtxdg, lxqt-qtplugin and libfm-qt installed, but those who compile from the sources should know where to find the latest Qt5 version of lxqt-build-tools (https://github.com/lxqt/lxqt-build-tools/releases/tag/0.13.0).

**Comment by Chiitoo** [comment]
> Of course, for a long time, users might need to keep Qt5-based packages of libqtxdg, lxqt-qtplugin and libfm-qt installed

Is this referring to applications outside of the LXQt project that might be using those, or some other reason?

Also, as a sidenote, should 'lxqt-build-tools' perhaps have a build-time dependency on Qt Linguist?

Currently only Qt in general is mentioned, but 'lxqt-build-tools' doesn't seem to care if Qt Linguist is installed or not.

Other packages will care though, such as 'lxqt-menu-data', which currently only mentions 'lxqt-build-tools' as a build-time dependency.

I suppose most distributions will automagically have Qt Linguist around if Qt is installed, but not all of them do.

**Comment by stefonarch** [comment]
`lxqt-menu-data` doesn't use linguist, so it's fine. All others which use it `should` have set it in CMakeList.txt.

**Comment by tsujan** [comment]
> Is this referring to applications outside of the LXQt project

Yes. By installing the latest Qt5-based versions of libqtxdg, lxqt-qtplugin and libfm-qt parallel to their new versions (or keeping them installed), those apps could be styled like Qt6 apps and have LXQt file dialog (if they need it).

**Comment by Chiitoo** [comment]
> `lxqt-menu-data` doesn't use linguist, so it's fine. All others which use it `should` have set it in CMakeList.txt.

Yeah, not directly, but in a kind of a roundabout way:

```
-- Could NOT find Qt6LinguistTools (missing: Qt6LinguistTools_DIR)
CMake Error at /usr/share/cmake/lxqt2-build-tools/modules/LXQtTranslateTs.cmake:62 (find_package):
  Found package configuration file:

    /usr/lib64/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find required Qt component "LinguistTools".

  Expected Config file at
  "/usr/lib64/cmake/Qt6LinguistTools/Qt6LinguistToolsConfig.cmake" does NOT
  exist
```

But yeah, I doubt users would see this without manually doing everything, as other packages will likely satisfy the requirement beforehand.

> Yes. By installing the latest Qt5-based versions of libqtxdg, lxqt-qtplugin and libfm-qt parallel to their new versions (or keeping them installed), those apps could be styled like Qt6 apps and have LXQt file dialog (if they need it).

Right, I did not think of the styles actually... need to keep that in mind while packaging things.

Thanks!

**Comment by Chiitoo** [comment]
Oh, I remembered I had been originally wondering about this with the initial package of 'lxqt-menu-data' too, because a CI build hit the issue, and I was then wondering if I should just depend on Qt Linguist via 'lxqt-build-tools' or the package itself.

Ended up going with the package itself, in case there is a use-case for 'lxqt-build-tools' without Qt Linguist.

**Pull request merged**
