### PR TITLE
Wip lxqt2 qt6

### PR DESCRIPTION
**Pull request by luis-pereira**
In progress Qt6 port.

### CODE REVIEW

**Comment by tsujan** [comment]
Added these drafts too:

https://github.com/lxqt/libqtxdg/pull/272

https://github.com/lxqt/libfm-qt/pull/778

https://github.com/lxqt/lxqt-qtplugin/pull/74

**Comment by luis-pereira** [comment]
I also have a `libqtxdg` but saw that you already pushed one.
We need something to keep track of it.

I renamed lxqt to lxqt2. This way we can have lxqt and lxqt2 installed at the same time.

**Comment by tsujan** [comment]
> I also have a libqtxdg but saw that you already pushed one.

I made a draft to prevent duplicate work. @stefonarch and I have tested the above branches. Of course, they'll need changes, especially because of `qtxdg-mat` and also after the current draft.

> I renamed lxqt to lxqt2. This way we can have lxqt and lxqt2 installed at the same time.

I think that's the best approach.

**Comment by palinek** [comment]
> I renamed lxqt to lxqt2

Wouldn't it be better to follow Qt main version (i.e. lxqt6)?

Why is this PR based on outdated commit?

**Comment by luis-pereira** [comment]
Superseded by https://github.com/lxqt/lxqt-build-tools/pull/77

**Pull request closed without merging**
