### PR TITLE
WIP: Change UPDATE_TRANSLATIONS to use lxqt-transupdate

### PR DESCRIPTION
**Pull request by agaida**
We just compile translation files with cmake - that will make the whole
code easier and far more reproducible.

Not carefully tested yet.

### CODE REVIEW

**Comment by agaida** [comment]
default is UPDATE_TRANSLATIONS=OFF right now - and updating the strings within a build process don*t make sense at all in the workflow - it will change nothing for the created binaries, So it should be a decoupled task not bound to cmake - thats my whole point.

**Comment by PCMan** [comment]
@agaida updating translation files during build is actually not that bad and it's supported by Qt officially.
FYI: http://doc.qt.io/qt-5/cmake-manual.html
See qt5_create_translation()
quote:  
>  The qm files are generated in the build tree. Updating the translations can be done by adding the qm_files to the source list of your library/executable, so they are always updated, or by adding a custom target to control when they get updated/generated."

So I personally don't consider this bad practice.
If we really want to remove the update_translation stuff, at least replace it with a custom target that can still be triggered manually via cmake. Intltool from Gnome also does similar things.

**Comment by agaida** [comment]
@PCMan - i just replaced the current code with a call to lxqt-transupdate - seems to work fine :)

```diff
-    if(TR_USE_QT5)
-        # Qt5
-        if (TR_UPDATE_TRANSLATIONS)
-            qt5_patched_create_translation(QMS
-                ${TR_SOURCES}
-                ${templateFile}
-                OPTIONS ${TR_UPDATE_OPTIONS}
-            )
-            qt5_patched_create_translation(QM
-                ${TR_SOURCES}
-                ${tsFiles}
-                OPTIONS ${TR_UPDATE_OPTIONS}
-            )
-        else()
-            qt5_patched_add_translation(QM ${tsFiles})
-        endif()
+    # Qt5
+    if (TR_UPDATE_TRANSLATIONS)
+        message("Running lxqt-transupdate: ")
+        execute_process(
+            COMMAND lxqt-transupdate
+            WORKING_DIRECTORY ..
+            OUTPUT_VARIABLE outVar
+        )
+        message(${outVar})
+        qt5_patched_add_translation(QM ${tsFiles})
```

**Comment by agaida** [comment]
@PCMan - and you are right  - never thought of the use case just to change some sources, doing an out of tree build and if it works fine and one is satified with the changes one could commit  the source and resulting translation changes together. Sorry, my bad, should write code far often :) .

**Pull request closed without merging**
